name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  status:
    description: 'Status of the last job (`success`, `failure`, or `canceled`)'
    required: true
  webhook_url:
    description: "Microsoft Teams webhook URL for posting the message"
    required: false
  card_name:
    description: "The name of the incoming card"
    default: "Github Actions Notifier"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'